
CREATE TABLE `DEMO_PRODUCT_TYPE` (
  `PRODUCT_ID` VARCHAR(64) NOT NULL COMMENT '产品ID',
  `PRODUCT_CODE` VARCHAR(64) NOT NULL COMMENT '产品编码',
  `PRODUCT_NAME` VARCHAR(64) NOT NULL COMMENT '产品名称',
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE `DEMO_PRODUCT_STORAGE` (
  `INVENTORY_ID` VARCHAR(64) NOT NULL COMMENT '库存单ID',
  `PRODUCT_CODE` VARCHAR(64) NOT NULL COMMENT '产品编码',
  `STOCK` INT(11) DEFAULT NULL COMMENT '库存量',
  PRIMARY KEY (`INVENTORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `DEMO_PRODUCT_SALES_VOLUME` (
  `SALES_ITEM_ID` VARCHAR(64) NOT NULL COMMENT '出货单ID',
  `PRODUCT_CODE` VARCHAR(64) NOT NULL COMMENT '产品编码',
  `PRODUCT_NUMBER` INT(11) NOT NULL COMMENT '出货量',
  PRIMARY KEY (`SALES_ITEM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

