server:
    port: 8080

jdbc:
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/euler_demo2?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8"
    user: "root"
    password: "111111"
    maxPoolSize: 20

spring:
    thymeleaf:
        cache: false

server:
    tomcat:
        access_log_enabled: true
        basedir: target/tomcat

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

application:
    name: euler-demo-third
    sales:
        tendency:
            message: \u9500\u552E\u8D8B\u52BF
        month:
            message: \u9500\u552E\u7EDF\u8BA1